name: flutter_stacked_starter
description: Stater app for creating scalable mobile apps with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Stacked State Management
  stacked: ^3.2.5
  stacked_services: ^1.0.2
  stacked_generator: ^1.3.2

  # Data Models
  freezed_annotation:
  json_annotation: ^4.0.1

  # UI
  cupertino_icons: ^1.0.2

  # Network
  dio: ^5.2.1+1
  in_app_update:
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Code Generation
  build_runner:

  # Data Models
  freezed:
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
